---
name: Build
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:
   # Map the workflow outputs to job outputs
    outputs:
      workflow_output:
        description: "Build output"
        value: ${{ jobs.go_build.outputs.build_output_failure }} 

jobs:
  go_build:
    name: HydraGon
    runs-on: ubuntu-latest
    outputs:
      build_output_failure: ${{ steps.hydra_build_failure.outputs.build_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Build HydraGon
        run: go build -tags netgo -o hydra -a -installsuffix cgo -ldflags="-s -w -linkmode external -extldflags \"-static\" -X \"github.com/Hydra-Chain/hydragon-node/versioning.Version=${GITHUB_REF_NAME}\" -X \"github.com/Hydra-Chain/hydragon-node/versioning.Commit=${GITHUB_SHA}\"" main.go && tar -czvf hydra.tar.gz hydra
        env:
          CC: gcc
          CXX: g++
          GOARC: amd64
          GOOS: linux

      - name: Build HydraGon Failed
        if: failure()
        id: hydra_build_failure
        run: echo "build_output=false" >> $GITHUB_OUTPUT

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: hydra
          path: hydra.tar.gz
          retention-days: 3

  go_build_reproducibility:
    name: Verify Build Reproducibility
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: 'Reproduce builds'
        continue-on-error: true
        run: |
          go build -o ./hydra-1 -trimpath -buildvcs=false
          go build -o ./hydra-2 -trimpath -buildvcs=false

          buildsha1=$(shasum -a256 ./hydra-1 | awk '{print $1}')
          buildsha2=$(shasum -a256 ./hydra-2 | awk '{print $1}')

          echo "Build 1 SHA: $buildsha1"
          echo "Build 2 SHA: $buildsha2"

          if [ "$buildsha1" != "$buildsha2" ]; then
            echo "Build artifact does not match original"
            exit 1
          else
            echo "Build artifact matches original"
          fi
